apiVersion: v1
kind: ConfigMap
metadata:
  name: standardnotes-configmap
data:
  LOG_LEVEL: {{ .Values.config.log_level | quote }}
  NODE_ENV: {{ .Values.config.node_env | quote }}
  VERSION: {{ .Values.config.version | quote }}

  AUTH_JWT_SECRET: {{ required "Required for safe encryption, generate with $ openssl rand -hex32" .Values.config.auth_jwt_secret | quote }}
  JWT_SECRET: {{ required "Required for safe encryption, generate with $ openssl rand -hex32" .Values.config.jwt_secret | quote }}
  LEGACY_JWT_SECRET: {{ required "Required for safe encryption, generate with $ openssl rand -hex32" .Values.config.legacy_jwt_secret | quote }}
  PSEUDO_KEY_PARAMS_KEY: {{ required "Required for safe encryption, generate with $ openssl rand -hex32" .Values.config.pseudo_key_params_key | quote }}
  ENCRYPTION_SERVER_KEY: {{ required "Required for safe encryption, generate with $ openssl rand -hex32" .Values.config.encryption_server_key | quote }}

  EXPOSED_PORT: {{ .Values.config.exposed_port | quote }}
  PORT: {{ .Values.config.port | quote }}

  DB_HOST: {{ .Values.config.db.host | quote }}
  DB_REPLICA_HOST: {{ .Values.config.db.replica_host | quote }}
  DB_PORT: {{ .Values.config.db.port | quote }}
  DB_DATABASE: {{ .Values.config.db.database| quote  }}
  DB_USERNAME: {{ .Values.config.db.username | quote }}
  DB_PASSWORD: {{ .Values.config.db.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.config.db.password | quote }}
  MYSQL_USER: {{ .Values.config.db.username | quote }}
  MYSQL_PASSWORD: {{ .Values.config.db.password | quote }}
  MYSQL_DATABASE: {{ .Values.config.db.database | quote }}
  DB_DEBUG_LEVEL: {{ .Values.config.db.debug_level | quote }}
  DB_MIGRATIONS_PATH: "dist/migrations/*.js"

  REDIS_URL: {{ .Values.config.redis.url | quote }}

  SNS_TOPIC_ARN: {{ .Values.config.aws.sns_topic_arn | quote }}
  SNS_AWS_REGION: {{ .Values.config.aws.sns_aws_region | quote }}
  SQS_QUEUE_URL: {{ .Values.config.aws.sqs_queue_url | quote }}
  SQS_AWS_REGION: {{ .Values.config.aws.sqs_aws_region | quote }}
  S3_AWS_REGION: {{ .Values.config.aws.s3_aws_region | quote }}
  S3_BACKUP_BUCKET_NAME: {{ .Values.config.aws.s3_backup_bucket_name | quote }}

  REDIS_EVENTS_CHANNEL: {{ .Values.config.redis.events_channel | quote }}

  AUTH_SERVER_URL: {{ .Values.config.auth_server_url | quote }}

  EMAIL_ATTACHMENT_MAX_BYTE_SIZE: {{ .Values.config.email_attachment_max_byte_size | quote }}

  REVISIONS_FREQUENCY: {{ .Values.config.revisions_frequency | quote }}

  # (Optional) New Relic Setup
  NEW_RELIC_ENABLED: {{ .Values.config.new_relic.enabled | quote }}
  NEW_RELIC_APP_NAME: {{ .Values.config.new_relic.app_name | quote }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.config.new_relic.license_key | quote }}
  NEW_RELIC_NO_CONFIG_FILE: {{ .Values.config.new_relic.no_config_file | quote }}
  NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: {{ .Values.config.new_relic.distributed_tracing_enabled | quote }}
  NEW_RELIC_LOG_ENABLED: {{ .Values.config.new_relic.log_enabled | quote }}
  NEW_RELIC_LOG_LEVEL: {{ .Values.config.new_relic.log_level | quote }}


  # this is coming from docker/auth.env in the repo
  SYNCING_SERVER_JS_URL: {{ .Values.config.syncing_server_js_url | quote }}

  # this is double REDIS_EVENTS_CHANNEL: "api-gateway-events"
