apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  mysqld.cnf: |
    [mysqld]
    pid-file	= /var/run/mysqld/mysqld.pid
    socket		= /var/run/mysqld/mysqld.sock
    datadir		= /var/lib/mysql
    #log-error	= /var/log/mysql/error.log
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    bind_address=0.0.0.0
