---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: apps
spec:
  storageClassName: ""
  selector:
    matchLabels:
      claimer: mysql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: import
  namespace: apps
spec:
  storageClassName: ""
  selector:
    matchLabels:
      claimer: import
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: apps
spec:
  storageClassName: ""
  selector:
    matchLabels:
      claimer: redis
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

