config:
  log_level: info
  node_env: production
  version: local
  exposed_port: 3000
  port: 3000
  email_attachment_max_byte_size: 10485760
  revisions_frequency: 300
  syncing_server_js_url: http://syncing-server-js:3000
  auth_server_url: http://auth:3000

  auth_jwt_secret: 4dbd87fb935049364f6b350538aa585d2642fde525ab0bda32ccbba1da6c52ed
  jwt_secret: 94e1fabff92eb1d0204eae9f06042fede0b639411f408f4f9d84fbb0e104ba5e
  legacy_jwt_secret: cb383493eac2be55d93a39a1201fb96f99aeb00a665101886c1a5958751a714a
  pseudo_key_params_key: e46a8ffa656008ea549bf3ab1c5a5fe28eaddfce8537d07861e5cb7c3400f520
  encryption_server_key: f2950f3a703aff26e67bfd4b6c27140a4a4ee48629e445b577ae6a5bb212779b

  db:
    host: db
    replica_host: db
    port: 3306
    username: std_notes_user
    password: changeme123
    database: standard_notes_db
    debug_level: all
    migrations_path: dist/migrations/*.js
  
  redis:
    url: cache://cache
    events_channel: events

  aws:
    sns_topic_arn: x
    sns_aws_region: x
    sqs_queue_url: x
    sqs_aws_region: x
    s3_aws_region: x
    s3_backup_bucket_name: x

  new_relic:
    enabled: false
    app_name: Syncing Server JS
    license_key: x
    no_config_file: true
    distributed_tracing_enabled: false
    log_enabled: false
    log_level: info