---
apiVersion: v2
appVersion: 0.20.0
description: The to-do app to organize your life
name: vikunja
version: 0.1.0
keywords:
  - vikunja
  - to-do
  - tasks
  - calendar
  - kanban
home: https://github.com/Yan-Solo/helm-charts/tree/main/stable/vikunja
icon: https://vikunja.io/images/vikunja-logo.svg
sources:
  - https://kolaente.dev/vikunja/api
  - https://kolaente.dev/vikunja/frontend
  - https://hub.docker.com/r/vikunja/api
  - https://hub.docker.com/r/vikunja/frontend
  - https://vikunja.io/docs/
maintainers:
  - name: Yan-Solo
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 0.2.2
  - name: postgresql
    version: 12.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
